DLLS= $(MAKDIR)\admin.dll \
 $(MAKDIR)\adminlog.dll \
 $(MAKDIR)\autoattach.dll \
 $(MAKDIR)\autoop.dll \
 $(MAKDIR)\autoreply.dll \
 $(MAKDIR)\awaynick.dll \
 $(MAKDIR)\blockuser.dll \
 $(MAKDIR)\bouncedcc.dll \
 $(MAKDIR)\buffextras.dll \
 $(MAKDIR)\cert.dll \
 $(MAKDIR)\certauth.dll \
 $(MAKDIR)\chansaver.dll \
 $(MAKDIR)\clientnotify.dll \
 $(MAKDIR)\crypt.dll \
 $(MAKDIR)\disconkick.dll \
 $(MAKDIR)\fail2ban.dll \
 $(MAKDIR)\keepnick.dll \
 $(MAKDIR)\kickrejoin.dll \
 $(MAKDIR)\lastseen.dll \
 $(MAKDIR)\nickserv.dll \
 $(MAKDIR)\notes.dll \
 $(MAKDIR)\partyline.dll \
 $(MAKDIR)\perform.dll \
 $(MAKDIR)\q.dll \
 $(MAKDIR)\raw.dll \
 $(MAKDIR)\route_replies.dll \
 $(MAKDIR)\savebuff.dll \
 $(MAKDIR)\schat.dll \
 $(MAKDIR)\simple_away.dll \
 $(MAKDIR)\stickychan.dll \
 $(MAKDIR)\watch.dll \
 $(MAKDIR)\webadmin.dll \
 $(MAKDIR)\extra\antiidle.dll \
 $(MAKDIR)\extra\autocycle.dll \
 $(MAKDIR)\extra\autovoice.dll \
 $(MAKDIR)\extra\away.dll \
 $(MAKDIR)\extra\block_motd.dll \
 $(MAKDIR)\extra\clearbufferonmsg.dll \
 $(MAKDIR)\extra\ctcpflood.dll \
 $(MAKDIR)\extra\dcc.dll \
 $(MAKDIR)\extra\fakeonline.dll \
 $(MAKDIR)\extra\flooddetach.dll \
 $(MAKDIR)\extra\imapauth.dll \
 $(MAKDIR)\extra\listsockets.dll \
 $(MAKDIR)\extra\log.dll \
 $(MAKDIR)\extra\motdfile.dll \
 $(MAKDIR)\extra\notify_connect.dll \
 $(MAKDIR)\extra\send_raw.dll \
 $(MAKDIR)\extra_win32\blockserver.dll \
 $(MAKDIR)\extra_win32\block_lagchk.dll \
 $(MAKDIR)\extra_win32\broadcastquery.dll \
 $(MAKDIR)\extra_win32\certchecker.dll \
 $(MAKDIR)\extra_win32\clientpart.dll \
 $(MAKDIR)\extra_win32\colloquy.dll \
 $(MAKDIR)\extra_win32\fish.dll \
 $(MAKDIR)\extra_win32\fix_lagchk.dll \
 $(MAKDIR)\extra_win32\highlightattach.dll \
 $(MAKDIR)\extra_win32\identserver.dll \
 $(MAKDIR)\extra_win32\ignore.dll \
 $(MAKDIR)\extra_win32\kicklog.dll \
 $(MAKDIR)\extra_win32\noctcp.dll \
 $(MAKDIR)\extra_win32\noreconnectonkill.dll \
 $(MAKDIR)\extra_win32\notify.dll \
 $(MAKDIR)\extra_win32\partdetach2.dll \
 $(MAKDIR)\extra_win32\prowl.dll \
 $(MAKDIR)\extra_win32\rawlog.dll \
 $(MAKDIR)\extra_win32\timed_perform.dll \
 $(MAKDIR)\extra_win32\twitter.dll \
 $(MAKDIR)\extra_win32\watch_only_detached.dll \
 $(MAKDIR)\extra_win32\win32_service_helper.dll

OBJS= $(MAKDIR)\admin.obj \
 $(MAKDIR)\adminlog.obj \
 $(MAKDIR)\autoattach.obj \
 $(MAKDIR)\autoop.obj \
 $(MAKDIR)\autoreply.obj \
 $(MAKDIR)\awaynick.obj \
 $(MAKDIR)\blockuser.obj \
 $(MAKDIR)\bouncedcc.obj \
 $(MAKDIR)\buffextras.obj \
 $(MAKDIR)\cert.obj \
 $(MAKDIR)\certauth.obj \
 $(MAKDIR)\chansaver.obj \
 $(MAKDIR)\clientnotify.obj \
 $(MAKDIR)\crypt.obj \
 $(MAKDIR)\disconkick.obj \
 $(MAKDIR)\fail2ban.obj \
 $(MAKDIR)\keepnick.obj \
 $(MAKDIR)\kickrejoin.obj \
 $(MAKDIR)\lastseen.obj \
 $(MAKDIR)\nickserv.obj \
 $(MAKDIR)\notes.obj \
 $(MAKDIR)\partyline.obj \
 $(MAKDIR)\perform.obj \
 $(MAKDIR)\q.obj \
 $(MAKDIR)\raw.obj \
 $(MAKDIR)\route_replies.obj \
 $(MAKDIR)\savebuff.obj \
 $(MAKDIR)\schat.obj \
 $(MAKDIR)\simple_away.obj \
 $(MAKDIR)\stickychan.obj \
 $(MAKDIR)\watch.obj \
 $(MAKDIR)\webadmin.obj \
 $(MAKDIR)\extra\antiidle.obj \
 $(MAKDIR)\extra\autocycle.obj \
 $(MAKDIR)\extra\autovoice.obj \
 $(MAKDIR)\extra\away.obj \
 $(MAKDIR)\extra\block_motd.obj \
 $(MAKDIR)\extra\clearbufferonmsg.obj \
 $(MAKDIR)\extra\ctcpflood.obj \
 $(MAKDIR)\extra\dcc.obj \
 $(MAKDIR)\extra\fakeonline.obj \
 $(MAKDIR)\extra\flooddetach.obj \
 $(MAKDIR)\extra\imapauth.obj \
 $(MAKDIR)\extra\listsockets.obj \
 $(MAKDIR)\extra\log.obj \
 $(MAKDIR)\extra\motdfile.obj \
 $(MAKDIR)\extra\notify_connect.obj \
 $(MAKDIR)\extra\send_raw.obj \
 $(MAKDIR)\extra_win32\blockserver.obj \
 $(MAKDIR)\extra_win32\block_lagchk.obj \
 $(MAKDIR)\extra_win32\broadcastquery.obj \
 $(MAKDIR)\extra_win32\certchecker.obj \
 $(MAKDIR)\extra_win32\clientpart.obj \
 $(MAKDIR)\extra_win32\colloquy.obj \
 $(MAKDIR)\extra_win32\fish.obj \
 $(MAKDIR)\extra_win32\fix_lagchk.obj \
 $(MAKDIR)\extra_win32\highlightattach.obj \
 $(MAKDIR)\extra_win32\identserver.obj \
 $(MAKDIR)\extra_win32\ignore.obj \
 $(MAKDIR)\extra_win32\kicklog.obj \
 $(MAKDIR)\extra_win32\noctcp.obj \
 $(MAKDIR)\extra_win32\noreconnectonkill.obj \
 $(MAKDIR)\extra_win32\notify.obj \
 $(MAKDIR)\extra_win32\partdetach2.obj \
 $(MAKDIR)\extra_win32\prowl.obj \
 $(MAKDIR)\extra_win32\rawlog.obj \
 $(MAKDIR)\extra_win32\timed_perform.obj \
 $(MAKDIR)\extra_win32\twitter.obj \
 $(MAKDIR)\extra_win32\watch_only_detached.obj \
 $(MAKDIR)\extra_win32\win32_service_helper.obj

